site_name: jsPsych in Qualtrics
theme: readthedocs
repo_url: 'https://github.com/kywch/jsPsych-in-Qualtrics/'
repo_name: 'kywch/jsPsych-in-Qualtrics'
edit_uri: ''
docs_dir: 'mkdocs'
nav:
- Introduction: 'index.md'
- Hosting jsPsych: 'github-pages.md'
- Hello world!: 'hello-world.md'
- Reaction-time task: 'rt-task.md'
site_author: 'Kyoung Whan Choe'
site_description: 'Step-by-step tutorials and examples on adding jsPsych cognitive tasks to Qualtrics'
copyright: 'Copyright &copy; 2020 <a href="https://kywch.github.io/" target="_blank">Kyoung Whan Choe</a>.'
google_analytics:
- 'UA-102316-3'
- 'auto'